#!/usr/bin/env node
/**
 * AI 日报/周报生成脚本
 * 整合量子位等内容，生成格式化的日报/周报
 */

const fs = require('fs');
const path = require('path');

// 读取配置文件
function loadConfig(configPath) {
  if (!fs.existsSync(configPath)) {
    throw new Error(`Config file not found: ${configPath}`);
  }
  return JSON.parse(fs.readFileSync(configPath, 'utf-8'));
}

// 读取抓取的文章数据
function loadArticles(dataPath) {
  if (!fs.existsSync(dataPath)) {
    return [];
  }
  return JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
}

// 分类文章
function categorizeArticles(articles) {
  const categories = {
    '大模型/AI技术': [],
    '自动驾驶': [],
    '机器人': [],
    '企业动态': [],
    '产品发布': [],
    '其他': []
  };

  for (const article of articles) {
    const title = article.title || '';
    const cats = article.categories || [];
    
    // 根据标题和分类自动分类
    if (title.includes('GPT') || title.includes('模型') || title.includes('AI') || 
        title.includes('智能体') || title.includes('Agent') || cats.some(c => c.includes('AI'))) {
      categories['大模型/AI技术'].push(article);
    } else if (title.includes('自动驾驶') || title.includes('智驾') || title.includes('端到端') ||
               title.includes('蔚来') || title.includes('小鹏') || title.includes('特斯拉')) {
      categories['自动驾驶'].push(article);
    } else if (title.includes('机器人') || title.includes('具身') || title.includes('Figure')) {
      categories['机器人'].push(article);
    } else if (title.includes('发布') || title.includes('上线') || title.includes('推出')) {
      categories['产品发布'].push(article);
    } else if (title.includes('收购') || title.includes('融资') || title.includes('盈利')) {
      categories['企业动态'].push(article);
    } else {
      categories['其他'].push(article);
    }
  }

  // 过滤空分类
  return Object.fromEntries(Object.entries(categories).filter(([_, v]) => v.length > 0));
}

// 生成日报
function generateDailyReport(articles, config) {
  const today = new Date().toLocaleDateString('zh-CN');
  const categorized = categorizeArticles(articles);
  
  let report = `# 🤖 AI 日报 - ${today}\n\n`;
  report += `> 专为传统车企 AI 团队定制\n`;
  report += `> 信息源：量子位、机器之心等\n\n`;

  // 摘要统计
  const totalArticles = articles.length;
  report += `## 📊 今日概览\n\n`;
  report += `- 收录文章：${totalArticles} 篇\n`;
  report += `- 时间范围：过去 24 小时\n`;
  report += `- 核心领域：${Object.keys(categorized).join('、')}\n\n`;

  // 核心层（可直接落地）
  report += `---\n\n`;
  report += `## 🔧 核心层（可直接落地）\n\n`;
  report += `**定义**：可被企业规模化开发使用的开源项目、模型、新范式\n\n`;
  
  const coreCats = ['大模型/AI技术', '产品发布'];
  let hasCore = false;
  for (const cat of coreCats) {
    if (categorized[cat]?.length > 0) {
      hasCore = true;
      for (const article of categorized[cat].slice(0, 3)) {
        report += `### ${article.title}\n\n`;
        report += `- 来源：[量子位](${article.link})\n`;
        report += `- 时间：${new Date(article.pubDate).toLocaleDateString('zh-CN')}\n`;
        if (article.description) {
          report += `- 摘要：${article.description}\n`;
        }
        report += `\n`;
      }
    }
  }
  if (!hasCore) {
    report += `*今日暂无核心层更新*\n\n`;
  }

  // 近层（行业前沿）
  report += `---\n\n`;
  report += `## 📡 近层（行业前沿，值得跟踪）\n\n`;
  report += `**定义**：行业动态、产品发布、技术路线选择\n\n`;
  
  const nearCats = ['自动驾驶', '机器人', '企业动态'];
  let hasNear = false;
  for (const cat of nearCats) {
    if (categorized[cat]?.length > 0) {
      hasNear = true;
      for (const article of categorized[cat].slice(0, 2)) {
        report += `- **${article.title}** [链接](${article.link})\n`;
      }
    }
  }
  if (!hasNear) {
    report += `*今日暂无近层更新*\n`;
  }
  report += `\n`;

  // 分析与建议
  report += `---\n\n`;
  report += `## 💡 分析与建议\n\n`;
  report += `**针对传统合资车企背景**：\n\n`;
  report += `1. **资源约束下的策略**：关注开源项目和可快速试用的工具，避免重复造轮子\n`;
  report += `2. **跟上头部节奏**：重点跟踪特斯拉、小鹏、华为等的技术路线选择\n`;
  report += `3. **内部推进建议**：建议组织小规模技术分享会，推动 AI 工具在内部的认知普及\n\n`;

  // -footer
  report += `---\n\n`;
  report += `*Generated by AI News Digest Skill*\n`;

  return report;
}

// 生成周报
function generateWeeklyReport(articles, config) {
  const today = new Date().toLocaleDateString('zh-CN');
  const weekStart = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toLocaleDateString('zh-CN');
  const categorized = categorizeArticles(articles);
  
  let report = `# 📰 AI 周报 (${weekStart} ~ ${today})\n\n`;
  report += `> 专为传统车企 AI 团队定制\n`;
  report += `> 本周核心要点 + 分析建议\n\n`;

  // 本周统计
  const totalArticles = articles.length;
  report += `## 📊 本周概览\n\n`;
  report += `- 收录文章：${totalArticles} 篇\n`;
  report += `- 时间范围：本周一至周日\n`;
  report += `- 重点关注：${Object.keys(categorized).join('、')}\n\n`;

  // 本周十大要闻
  report += `---\n\n`;
  report += `## 🔥 本周十大要闻\n\n`;
  const topArticles = articles.slice(0, 10);
  for (let i = 0; i < topArticles.length; i++) {
    const article = topArticles[i];
    report += `${i + 1}. **${article.title}**\n`;
    report += `   - [链接](${article.link}) | ${new Date(article.pubDate).toLocaleDateString('zh-CN')}\n\n`;
  }

  // 分层汇总
  report += `---\n\n`;
  report += `## 📑 分层汇总\n\n`;
  
  for (const [cat, items] of Object.entries(categorized)) {
    report += `### ${cat} (${items.length} 篇)\n\n`;
    for (const article of items.slice(0, 5)) {
      report += `- ${article.title}\n`;
    }
    report += `\n`;
  }

  // 深度分析
  report += `---\n\n`;
  report += `## 🎯 深度分析\n\n`;
  report += `### 技术趋势洞察\n\n`;
  report += `基于本周信息，观察到以下趋势：\n\n`;
  report += `1. **大模型应用加速**：多篇文章涉及 AI Agent、智能体等应用落地\n`;
  report += `2. **自动驾驶端到端**：端到端方案持续升温，传统车企需加快跟进\n`;
  report += `3. **企业 AI 化**：从工具到工作伙伴的转变趋势明显\n\n`;

  report += `### 针对传统合资车企的建议\n\n`;
  report += `**核心策略**：\n\n`;
  report += `1. **建立信息雷达**：每天 10 分钟浏览核心信息源，保持技术敏感度\n`;
  report += `2. **试点先行**：选择 1-2 个场景进行 AI 工具试点，积累经验后再推广\n`;
  report += `3. **生态合作**：关注开源社区和供应商方案，降低自研成本\n`;
  report += `4. **人才培养**：鼓励团队尝试新工具，建立内部知识分享机制\n\n`;

  report += `**下周关注重点**：\n\n`;
  report += `- 持续跟踪大模型在企业场景的落地案例\n`;
  report += `- 关注头部车企的端到端自动驾驶进展\n`;
  report += `- 留意 AI 基础设施（算力、数据）相关动态\n\n`;

  // footer
  report += `---\n\n`;
  report += `*Generated by AI News Digest Skill*\n`;

  return report;
}

function main() {
  try {
    const args = process.argv.slice(2);
    const configPath = args.find((_, i) => args[i-1] === '--config') || path.join(__dirname, '../references/config.json');
    const dataPath = args.find((_, i) => args[i-1] === '--data') || './articles.json';
    const type = args.find((_, i) => args[i-1] === '--type') || 'daily'; // daily or weekly
    const outputPath = args.find((_, i) => args[i-1] === '--output');

    const config = loadConfig(configPath);
    const articles = loadArticles(dataPath);

    let report;
    if (type === 'weekly') {
      report = generateWeeklyReport(articles, config);
    } else {
      report = generateDailyReport(articles, config);
    }

    if (outputPath) {
      fs.writeFileSync(outputPath, report, 'utf-8');
      console.error(`[INFO] Report saved to ${outputPath}`);
    } else {
      console.log(report);
    }

  } catch (error) {
    console.error('[ERROR]', error.message);
    process.exit(1);
  }
}

main();
